# Generated by Django 4.2.6 on 2023-11-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_category_code_alter_listings_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
