# Generated by Django 4.2.6 on 2023-11-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='kategory',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_category', to='auctions.category'),
        ),
    ]
