# Generated by Django 4.2.6 on 2023-11-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='kategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_category', to='auctions.category'),
        ),
    ]
